name: Post

on:
  workflow_dispatch:
  schedule:
  - cron: '0 17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v3
    - name: Configure Python with pip cache
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        curl -o /tmp/bluesky-post.gz --fail https://danp128.s3.amazonaws.com/bluesky-post.gz
        gunzip /tmp/bluesky-post.gz
        chmod +x /tmp/bluesky-post
        mkdir -p "$HOME/bin"
        mv /tmp/bluesky-post "$HOME/bin"
        echo "$HOME/bin" >> "$GITHUB_PATH"
    - name: Install Playwright browser
      run: |
        shot-scraper install -b firefox
    - name: Configure Git for commits
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
    - name: Generate screenshot with shot-scraper and post
      env:
        BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
        BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
      run: bin/shot-and-post
    - name: Commit latest
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git push
