name: Tweet

on:
  workflow_dispatch:
  schedule:
  - cron: '0 17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Configure Python with pip cache
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
    - name: Cache Playwright browsers
      uses: actions/cache@v2
      with:
        path: ~/.cache/ms-playwright/
        key: ${{ runner.os }}-browsers
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Install Playwright browser
      run: |
        shot-scraper install -b firefox
    - name: Configure Git for commits
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
    - name: Generate screenshot with shot-scraper and tweet
      env:
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      run: |-
        set -eo pipefail
        latest="$(curl --fail https://health-infobase.canada.ca/src/data/covidLive/wastewater/covid19-wastewater.csv | grep Halifax | sort | tail -n1 | cut -d, -f1)"
        if cmp -s <(echo "$latest") latest-date; then
           exit 0
        fi
        echo "$latest" > latest-date
        last_year="$(date --date="$latest - 1 year" +"%Y-%m-%d")"
        url="https://health-infobase.canada.ca/covid-19/wastewater/?dateSel=customrange&regions=4&sdate=${last_year}&edate=${latest}&sort=asc&grid=1&showDailyValues=false"
        echo "$url"
        worked=0
        for _ in 0 1 2 3; do
          if shot-scraper -o /tmp/covid.png --retina -b firefox --selector-all '#graph-container > div > div' "$url"; then
            worked=1
            break
          fi
          sleep 10
        done
        if [ $worked -eq 0 ]; then
          exit 1
        fi
        tweet-images "COVID wastewater charts for the Halifax area as of $latest https://health-infobase.canada.ca/covid-19/wastewater/?dateSel=alltime&sort=asc&grid=1&regions=8&showDailyValues=false" \
          /tmp/covid.png --alt "Screenshot of the charts" > latest-tweet.md
    - name: Commit latest-tweet.md
      run: |-
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git push
